export interface PilotsStat {
    'Pilotenname':string
    'Einsaetze':number,
    'LandingStreak':number,
    'Tode':number,
    'Ejections':number,
    'Startzeit':number,
    'Landezeit':number,
    'Flugzeit':number,
    'Starts':number,
    'Landungen':number,
    'Verdienst':number,
    'Missionen gestartet':number,
    'erfolgreiche Missionen':number,
    'zuletzt gestartet von':string,
    'zuletzt gelandet in':string,
    'Flugzeugtyp':string,
    'zerstoerte Bodeneinheiten':number,
    'zerstoerte Strukturen':number,
    'zerstoerte Flugzeuge':number,
    'zerstoerte Helikopter':number,
    'zerstoerte Schiffe':number,
    'Bittersweet':number,
    'LSO Bewertungen':string,
    'Platzhalter1',
    'Platzhalter2',
    'Platzhalter3',
    'Platzhalter4',
    'Platzhalter6'
}